### ISSUE TITLE
Does this pose a risk to devices?

### ISSUE THREAD

**Issue by DataPools** [NoMod-Programming/StupidJailbreak#1]
I don't want to risk a bootloop or anything on my 6s. Is this safe to run?

**Comment by NoMod-Programming** [comment]
Right now, it won't get very far (it fails due to the lack of a symbol table in the dumped kernel), but it will not break anything at the moment. However, unless you are interested in running it and providing logs (which I would appreciate), or helping develop it directly, I would wait for a final release, eta around a week or two.

**Comment by DataPools** [comment]
Alright, how would I go about installing it and getting the logs?

Should I just use Cydia Impactor?

**Comment by NoMod-Programming** [comment]
If you have XCode, you can just build it from there and deploy it to your device. Then copy the output from the console and paste it in a new issue. From Cydia Impactor, I think you can do something similar, but I'm honestly not sure how to get the logs from a specific application. I can try to figure it out though, but I'm honestly not sure at the moment.

**Comment by NoMod-Programming** [comment]
May I close this issue now?
